app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'PostsController@getIndex'));


Route::group(array('prefix' => 'admin'), function() {

	Route::get('login', array('as' => 'admin.login', 'uses' => 'AdminAuthController@getLogin'));
	Route::post('login', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
	Route::get('logout', array('as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));

});

Route::group(array('prefix' => 'admin', 'before' => 'auth'), function() {

	Route::resource('posts', 'AdminPostsController', array('except' => array('show')));

});

Route::post('filter/author/{id}', array('as' => 'filter.author', 'uses' => 'PostsController@getPostByAuthor'));
Route::get('post/{id}', array('as' => 'post', 'uses' => 'PostsController@getPost'))->where('id', '[1-9][0-9]*');

Route::post('/post/{post}/comment', array('as' => 'comment.create', 'uses' => 'CommentController@create'));

Route::resource('user', 'UsersController');
Route::resource('comments', 'CommentController', array('except' => array('show')));

Route::group(array('prefix' => 'api/v1'), function() {

	

});

Route::resource('feed', 'PostsController@json');

app/views/_layouts/default.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog</title>
	
	{{ HTML::style('css/blog-style.css') }}
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>
	
	<header>
		<div id="masthead">
			{{ link_to_route('home', 'Dempsey') }}
		</div>
		@if(!Auth::check())
			<div class="not-logged-in">
				<div class="button">
					{{ link_to_route('admin.login', 'Login') }}
				</div>
				<div class="button">
					{{ link_to_route('user.create', 'Sign Up') }}
				</div>
			</div>
		@else
			<div class="logged-in">
				<p>Logged in as: {{ Auth::user()->name }}</p>
				<div class="button">
					{{ link_to_route('admin.posts.create', 'Create Post') }}
				</div>
				<div class="button">
				 	@include('admin.auth.logout')
				</div>
			</div>
		@endif
	</header>
	<div class="messages">
		@if(Session::has('message'))
			<p class="alert">{{ Session::get('message') }}</p>
		@endif
	</div>
	<main>
		@yield('content')
	</main>

	<footer>
		<div class="container">
			&copy; {{ date('Y') }} Luke Hathaway | {{ link_to_route('admin.posts.index', 'Admin') }}
		</div>
	</footer>
	{{ HTML::script('//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js') }}
	{{ HTML::script('js/blog-script.js') }}
</body>
</html>

app/views/_layouts/layout.editor.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Blog</title>
	
	{{ HTML::style('css/blog-style.css') }}
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>
	
	<header>
		<div id="masthead">
			{{ link_to_route('home', 'Dempsey') }}
		</div>
		@if(!Auth::check())
			<div class="not-logged-in">
				<div class="button">
					{{ link_to_route('admin.login', 'Login') }}
				</div>
				<div class="button">
					{{ link_to_route('user.create', 'Sign Up') }}
				</div>
			</div>
		@else
			<div class="logged-in">
				<p>Logged in as: {{ Auth::user()->name }}</p>
				<div class="button">
				 	@include('admin.auth.logout')
				</div>
				<div class="button">
					{{ link_to_route('admin.posts.create', 'Create Post') }}
				</div>
			</div>
		@endif
	</header>

	<main>
		@yield('content')
	</main>

	<footer>
		<div class="container">
			&copy; {{ date('Y') }} Luke Hathaway | {{ link_to_route('admin.posts.index', 'Admin') }}
		</div>
	</footer>
	@include('partials.editor')
</body>
</html>