app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'PostsController@getIndex'));


Route::group(array('prefix' => 'admin'), function() {

	Route::get('login', array('as' => 'admin.login', 'uses' => 'AdminAuthController@getLogin'));
	Route::post('login', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
	Route::get('logout', array('as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));

});

Route::group(array('prefix' => 'admin', 'before' => 'auth'), function() {

	Route::resource('posts', 'AdminPostsController', array('except' => array('show')));

});

Route::post('filter/author/{id}', array('as' => 'filter.author', 'uses' => 'PostsController@getPostByAuthor'));
Route::get('post/{id}', array('as' => 'post', 'uses' => 'PostsController@getPost'))->where('id', '[1-9][0-9]*');

Route::post('/post/{post}/comment', array('as' => 'comment.create', 'uses' => 'CommentController@create'));

Route::resource('user', 'UsersController');
Route::resource('comments', 'CommentController', array('except' => array('show')));

Route::group(array('prefix' => 'api/v1'), function() {

	

});

Route::resource('feed', 'PostsController@json');

app/models/Post.php
<?php

class Post extends \Eloquent {

	/**
	* Validation rules
	*
	* @var array
	*/
	
	public static $rules = array(
		'title' => 'required|between:3,255',
		'body' => 'required',
		'user_id' => 'integer'
	);

	/**
	* The only fields that should be allowed to be mass assigned
	*
	* @var array
	*/

	protected $fillable = array('title', 'body', 'user_id');

	
	/**
	* User relationship
	*/

	public function user() {
		return $this->belongsTo('User');
	}

	/**
	* Comments relationship
	*/

	public function comments() {
		return $this->hasMany('Comment');
	}

}

app/controllers/PostsController.php
<?php

class PostsController extends \BaseController 
{

	public function getIndex() {

		$posts = Post::with('user')->orderBy('created_at', 'desc')->paginate(3);
		
		$posts->getFactory()->setViewName('pagination::simple');

		return View::make('posts.index', compact('posts'));

	}

	public function getPost($id) {

		$post = Post::with('user')->find($id);

    $comment = Comment::with('post', 'user')
                        ->where('post_id', '=', $post->id)
                        ->get();

    $user = Auth::user();
   	
		return View::make('posts.post', compact('post', 'comment', 'user', 'comment_user'));

	}

	public function getPostByAuthor($id) {

		$id = Input::get('user_id');

		$posts = Post::where('user_id', $id)->get();

		$author = User::where('id', $id)->get();

		return View::make('posts.filtered', compact('posts', 'id', 'author'));

	}

	public function json() {

		$today = new DateTime();

		return Post::select('users.name AS Author', 'posts.title AS Title', 'posts.body AS Body', 'posts.created_at AS Posted On')
								 ->join('users', 'posts.user_id', '=', 'users.id')
								 ->where('posts.created_at', '>', $today->modify('-2 days'))
								 ->orderBy('posts.created_at', 'desc')
								 ->get();

	}

}

app/views/admin/posts/create.blade.php
@extends('admin._layouts.admin')

@section('content')

	<h1>Create Post</h1>

	{{ Form::open(array('route' => 'admin.posts.store')) }}

		@include('admin.posts._partials.form')

	{{ Form::close() }}

@stop

app/views/admin/posts/edit.blade.php
@extends('admin._layouts.admin')

@section('content')

	<h1>Edit Post</h1>

	{{ Form::model($post, array('route' => array('admin.posts.update', $post->id), 'method' => 'put')) }}

		@include('admin.posts._partials.form')

	{{ Form::close() }}

@stop

app/views/admin/posts/index.blade.php
@extends('admin._layouts.admin')

@section('content')

	<h1>My Posts</h1>
	@if(count($posts))
		<ul id="post-list">
			@foreach($posts as $post)
				<li>
					{{ link_to_route('admin.posts.edit', $post->title, array($post->id)) }}
					{{ Form::open(array('route' => array('admin.posts.destroy', $post->id), 'method' => 'delete', 'class' => 'destroy')) }}
					{{ Form::submit('Delete', array('class' => 'delete')) }}
					{{ Form::close() }}
				</li>
			@endforeach
		</ul>

	@endif

@stop